### ISSUE TITLE
Triggering change-Event on the select

### ISSUE THREAD

**Issue by AVGP** [jamieholst/selectToAutocomplete#13]
I just had a use-case for capturing the change-event for the select being autocompleted.
I guess it would be nice to trigger the event from the update_select_value.

To make it work for me, I just added

``` javascript
context.$select_field.change();
```

in line 215 in the *.js.

**Comment by jamieholst** [comment]
Fixed here: https://github.com/JamieAppleseed/selectToAutocomplete/pull/14
