### ISSUE TITLE
Support multiple selections

### ISSUE THREAD

**Issue by littlefyr** [jamieholst/selectToAutocomplete#19]
It would be wonderful if you could support multiple select values. I rather like just comma separating the values and then growing the box size if it needs to wrap.

**Comment by jamieholst** [comment]
Agreed. This is, however, a task of the autocomplete plugin of choice, not something to be handled by selectToAutocomplete (for which the purpose is to convert a dropdown to an autocomplete field in mordern browsers based on the data in the dropdown options).
