### ISSUE TITLE
Selected attribute incorrect when 2 or more options have the same value

### ISSUE THREAD

**Issue by EpicCombover** [jamieholst/selectToAutocomplete#22]
Using the demo HTML, I added an extra option for APO/FPO with the value of US to the select like so:

```
<select name="Country" id="country-selector" autofocus="autofocus" autocorrect="off" autocomplete="off">
    <option selected="selected" value="US" data-relevancy-booster="3.5" data-alternative-spellings="US USA United States of America">United States</option>
    <option  value="US" data-relevancy-booster="2.5" data-alternative-spellings="APO/FPO">APO/FPO</option><option value="Afghanistan" data-alternative-spellings="AF">Afghanistan</option>
    <option value="Åland Islands" data-alternative-spellings="AX Aaland Aland" data-relevancy-booster="0.5">Åland Islands</option>
</select>
```

Using jQuery to find the selected option outputs the incorrect country:
$("#country-selector").find(':selected').text();

Expected: United States
Actual: APO/FPO

When I turn off selectToAutocomplete, I get the expected results.

**Comment by jamieholst** [comment]
Thanks for reporting this. I'm currently snowed under in work, but I've labelled this as a "bug" so it can hopefully get fixed soon.

**Comment by vmitchell85** [comment]
Not sure if it would make a difference but you are missing a closing > on your APO/FPO option tag...

**Comment by EpicCombover** [comment]
@vmitchell85  Thanks for catching that, I accidentally deleted the closing > when I pasted it.  The issue still exists though.

**Comment by jamieholst** [comment]
This has been fixed in the latest version of the plugin.
