### ISSUE TITLE
"Member not found" Error

### ISSUE THREAD

**Issue by vmitchell85** [jamieholst/selectToAutocomplete#23]
I am developing a contact us page and I'm using the validate plugin as well as the selectToAutocomplete plugin. Everything works great in Chrome but in IE the form will submit without validation and the browser shows the following error:

Message: Member not found.

Line: 2
Char: 30636
Code: 0
URI: jquery-1.7.1.min.js

Now, I do realize that the error is from my jquery file but when I remove the jquery statement that calls selectToAutocomplete everything works like normal.

Thanks,
- Vince

**Comment by jamieholst** [comment]
This sounds like a bug.. could you provide the jQuery statement (or at least the part that calls selectToAutocomplete).. e.g. is it chained? (Chaining should be possible, but maybe there's an IE issue with it.)

**Comment by vmitchell85** [comment]
Not sure I'm skilled enough with jquery to tell you if it's chained... I've uploaded it to my test site here: http://test.stickmanstudios.com/country/contactus.htm so you can see the page and code... Let me know if you need more info.

Thanks,
- Vince

**Comment by jamieholst** [comment]
Hi @vmitchell85 

Could you try the latest version (1.0.5) of the plugin? I've made the plugin skip initialization in IE7 and below so it doesn't fail. 

(See [this commit](https://github.com/JamieAppleseed/selectToAutocomplete/commit/3ec7a20ce724bfc5b7b542176db0db72d44b3913) for the fix.)

**Comment by weezer311** [comment]
I was having the same issue. I found the problem to be with the Doctype. I was using HTML 4.01 Transitional. I switched it to HTML 5 and it works. Likely something to do with how IE falls into quirks mode.

**Comment by timcooper** [comment]
Didn't see this issue before I made a [pull request](https://github.com/JamieAppleseed/selectToAutocomplete/pull/33), but it's a bug to do with the attribute copying (in the insert_text_field) in IE7. This particular error is coming from something like 
    $(element).attr('implementation', null)

I'm not sure why it throws this error for some attributes but not for most, but if we [check the original element's version of that attribute](https://github.com/timcooper/selectToAutocomplete/commit/6fbd845b4a5059759ffec4d1de52c983213e9029#L0R55) and only copy it if it is set we can get around all these problems.

**Comment by jamieholst** [comment]
Thanks for the fix Tim. It's been merged.
