### ISSUE TITLE
Text autoselect on input mouse click

### ISSUE THREAD

**Issue by serialc** [jamieholst/selectToAutocomplete#27]
In terms of usability I wonder if it wouldn't be helpful to have the input text be automatically and completely selected on mouse click as it currently is by default when you tab into the field.

Something like the following applied to the input field:

``` javascript
$('#inputid').click(function() { this.focus(); this.select(); });
```

Demo: http://jsfiddle.net/serialc/SfYDY/

**Comment by jamieholst** [comment]
Thanks for the pull request, closing this issue.
