### ISSUE TITLE
A blank search of more than 11 options displays out of order

### ISSUE THREAD

**Issue by adamjudd** [jamieholst/selectToAutocomplete#29]
This also happens when you simply press down in the text field, and appears that it is caused by something within selectToAutocomplete. I tried the dropdown using simply jQuery UI's autocomplete and a blank search returns the list alphabetically as expected - so it must me something with this plugin.

I'm still digging into the issue but thought I'd post now and see if anyone else has come against this too. From some testing, this only comes into affect when there is more than 10 options in the select. Exactly 10 options displays fine, 11 options shows this issue though. From what I can see, the middle option goes to position 1 and the original second option goes to where the middle option came from.

For example, `1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11` would become `6, 1, 3, 4, 5, 2, 7, 8, 9, 10, 11`

You can see this on the demo on your site as well. For what it's worth, the test I did had no additional weighting set per item. Setting both `sort` and `relevancy-sorting` to `false` removed this issue, but setting either to `true` showed the issue.

**Comment by adamjudd** [comment]
So digging further this relates to the sort function call, and seems that the sort function has some specific way of sorting matching values. In a blank search, all options have the same relevancy-score - of 0 - but sort seems to continually sort them in the same weird way, for 11 or more options it sorts the second option in the middle and the middle option first...

To see this in action, go to this page: http://www.breakingpar.com/bkp/home.nsf/0/87256B280015193F87256C8D00516B2E
1. Add 10 entries all with the same first and last name, and give each an age ascending from 1, so you have 10 entries ranging from 1 to 10.
2. Now sort those entries by first name. Keep clicking, and nothing changes.
3. Add another entry with an age of 11 and the same first/last name. Now keep clicking sort by first name. Watch the ages continue to re-arrange.

So unless there is some fix to sort, does this come down to not sorting options if no search text is given? Something like 
`if ( context.settings['relevancy-sorting'] && request.term != "" ) {`
in the `source` function for the jQuery UI adapter?

Actually, this issue may still present when arrays are sorted with a request term if a large chunk are the same relevancy. Should the sorting sort on both the relevancy and the value? Something like this:
`return (a['relevancy-score'] != b['relevancy-score']) ? b['relevancy-score'] - a['relevancy-score'] : (a['label'] < b['label']) ? -1 : 1;`

**Comment by adamjudd** [comment]
Huh, so this is browser specific - Take a look at this discussion as to why I saw it different depending on the array length in Chrome: http://code.google.com/p/v8/issues/detail?id=90

**Comment by jamieholst** [comment]
This has been fixed in the latest version of the plugin.
