### ISSUE TITLE
Doesn't Fire Change() events

### ISSUE THREAD

**Issue by kyeotic** [jamieholst/selectToAutocomplete#3]
If you have a .change() for the select that you turn into an autocomplete, it won't fire (despite the value changing). I haven't yet found a workaround.

**Comment by nogweii** [comment]
Is it perhaps because the select's value doesn't actually change? Instead it's a text input, which probably isn't inheriting the event handlers.

**Comment by jamieholst** [comment]
The select value is changing but it does so programatically – $select_field.val( '..' ) – which doesn't trigger a 'change' event. Only user-interaction with the select-tag itself will trigger it.

However, I'm closing this issue as this discussion is also taking place [over here](https://github.com/JamieAppleseed/selectToAutocomplete/pull/5). Hope that is OK :)
