### ISSUE TITLE
Not working in Android browser

### ISSUE THREAD

**Issue by anthonyxwatson** [jamieholst/selectToAutocomplete#35]
I'm on froyo, using the default (webkit) mobile browser. I get the input field, but no auto-complete.

**Comment by jamieholst** [comment]
The plugin is a "progressive enhancement", so it is only enabled in browsers that support its functionality. Older browsers will simply get the regular drop-down / select tag. This way the site and form never breaks and users can always make the necessary form selections, even if they are using an older browser.
