### ISSUE TITLE
Unable to delete once an option is selected

### ISSUE THREAD

**Issue by heisds** [jamieholst/selectToAutocomplete#37]
On this page:

http://baymard.com/labs/country-selector

If you 
1. select a country, but then 
2. delete the text, 
it goes back to showing the placeholder and the value of the input element being empty. However, on the example with the git repository, as well I what I currently have, there is no way to go back to having nothing selected once something is selected. I tried to look at the source of that page and tried a few things, but for the particular case we use it in, the country needs to be able to be removed.

**Comment by jamieholst** [comment]
This has been fixed in the latest version of the plugin.
