### ISSUE TITLE
Issue when using jquery ui greater than 1.8.23

### ISSUE THREAD

**Issue by daishi446** [jamieholst/selectToAutocomplete#44]
When using versions greater than 1.8.23  the first option in the list is not selected by default therefore it is not possible to complete the input just by hitting enter after typing rather the user must now at the very least hit the down key or use the mouse which ruins the whole point of the plugin.

**Comment by jamieholst** [comment]
The plugin demo has been updated to the latest versions of jQuery and jQuery UI, and these should work as expected now.
