### ISSUE TITLE
Strict relevancy does not play its role

### ISSUE THREAD

**Issue by trollfot** [jamieholst/selectToAutocomplete#45]
The regexp used to find the strict values is the same than the partial one and, therefore, the sorting is uncorrect.

I fixed the issue locally, by doing this :
-              matcher['strict'] = new RegExp( "^" + $.ui.autocomplete.escapeRegex( split_term[i] ), "i" );
-              matcher['strict'] = new RegExp( "^" + $.ui.autocomplete.escapeRegex( split_term[i] ) + "$", "i" );

**Comment by jamieholst** [comment]
The plugin's RegExp works as intended. 'strict' won't search inside terms (hence the "^" clause), but it should be a match as the user is typing the actual word. By adding the ending "$" clause, 'strict' would only match once the user had typed the entire term, which is not the behavior that was intended for the plugin. But there's of course no "right" or "wrong" implementation, so do continue using whichever logic you find the most appropriate for your site, and thanks for sharing, I'm sure others might prefer this logic too :)
