### ISSUE TITLE
Working with Spry Validation

### ISSUE THREAD

**Issue by hollingd** [jamieholst/selectToAutocomplete#47]
Hi,

Firstly I came across your blog post and it was exactly what I was looking for.  Great article and thank you for the code, it works a treat.

That was until I tried plugging it into a current form which uses Spry Validation.  For some reason I've got the Validation working find along with the autoComplete but it just wont submit the from.  I'm not sure what I'm missing and would really appreciate some assistance in getting this to work.

Regards
David.

**Comment by tobya** [comment]
Try posting your question on http://Stackoverflow.com  you might get more eyeballs
