### ISSUE TITLE
FF - Empty space at bottom of site: height of ul.ui-autocomplete added to bottom of document

### ISSUE THREAD

**Issue by KennyBrijs** [jamieholst/selectToAutocomplete#49]
Because of the `position: relative;` property on the `ul.ui-autocomplete` element, the country list is not taken out of the document flow.

This causes an empty space to occur at the bottom of the site in Firefox (see image at the bottom)

It’s not an issue with my own CSS, I’ve noticed more space appearing on [the officiall website](http://baymard.com/labs/country-selector) too. Not pointing fingers here, just clearing thing out ;)

Might it be a solution to actually put the .ui-autocomplete list _beneath the `<input>` element in the HTML_, instead of putting it at the end of the code and then giving it a relative position based on the `<input>`’s position on the page?

![firefox-empty-space](https://f.cloud.github.com/assets/1244206/89421/d5e270ae-653e-11e2-8ea7-4ed0b10df3a5.png)

**Comment by jamieholst** [comment]
This is a behavior of the chosen autocomplete plugin and site CSS. selectToAutocomplete should be agnostic in both regards, the demo (which relies on jQuery UI and some basic CSS) is simply to showcase the plugin's functionality.
