### ISSUE TITLE
Uncaught TypeError: Cannot read property 'msie' of undefined

### ISSUE THREAD

**Issue by nathanhornby** [jamieholst/selectToAutocomplete#50]
"msie is the flag on the jQuery.browser property, which was deprecated since version 1.3 and was removed in jQuery 1.9.0."

Issue only found in jQuery 1.9, and on Chrome. Have had to revert to 1.8.3 for now.

**Comment by nmpolo** [comment]
You can use the following code to allow the plugin to work for now:

``` javascript
jQuery.browser = {};
jQuery.browser.mozilla = /mozilla/.test(navigator.userAgent.toLowerCase()) && !/webkit/.test(navigator.userAgent.toLowerCase());
jQuery.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());
jQuery.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());
jQuery.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());
```

(See http://pupunzi.open-lab.com/2013/01/16/jquery-1-9-is-out-and-browser-has-been-removed-a-fast-workaround/)

**Comment by matthewmorek** [comment]
Does browser sniffing is really required for the plugin to run properly? This really needs to be fixed, as the plugin isn't compatible with any jQuery above 1.8.3.

**Comment by MichaelFBA** [comment]
+1

**Comment by nathanhornby** [comment]
Echoing @matthewmorek - what's the browser detection for anyway?

**Comment by iftomkins** [comment]
@nmpolo's solution worked for me. Only tested in Chrome so far.

**Comment by jamieholst** [comment]
Fixed in the latest version of the plugin.
