### ISSUE TITLE
Is there way to limit the amount of results?

### ISSUE THREAD

**Issue by firedev** [jamieholst/selectToAutocomplete#52]
It would be great to have an option of limiting the output so people would narrow their matches quicker.

**Comment by jamieholst** [comment]
This would be a feature of whichever autocomplete plugin you've chosen to use (selectToAutocomplete doesn't have to use jQuery UI, that is simply used for the demo). Unfortunately, I don't think jQuery UI has an option to limit the number of displayed options.

As a "hack" you could use CSS (see: nth-child) to hide any options after your desired cutoff.
