### ISSUE TITLE
Ordering, typing 'Ireland'

### ISSUE THREAD

**Issue by kevincannon** [jamieholst/selectToAutocomplete#58]
Typing Ireland doesn't perform very well.
It puts United Kingdom always above it. I suppose it's doing that because of Norther Ireland, which is good, but if I type 'Irel' then Ireland should be above The United Kingdom.

**Comment by jamieholst** [comment]
Simply adjust the relevancy boosters of the countries – the country list in the demo assigns UK a high relevancy booster to showcase the functionality, but these values should definitely be adjusted to suit the context of your site :)
