### ISSUE TITLE
will not work with jquery 1.9+

### ISSUE THREAD

**Issue by otmezger** [jamieholst/selectToAutocomplete#63]
I tried the plugin for my website using jquery 1.9+ but didn't work. 

We manage to get it working using the jquery migration plugin (https://github.com/jquery/jquery-migrate/). 

I think it's time to make an update to this very cool plugin :-)

**Comment by numediaweb** [comment]
+1 for this.
The plugin uses 1.8.1 while jQuery now is at 2.1.0 (as of now).
I get `Uncaught TypeError: Cannot read property 'msie' of undefined` because $.browser was removed from jQuery starting with version 1.9

**Comment by efaj** [comment]
It also seems to have issues with recent jQuery-UI versions

**Comment by MichaelFBA** [comment]
+1

**Comment by PV-Patrick** [comment]
Doesn't work properly with newer jQuery/UI. (excellent plugin otherwise)
+1

**Comment by daniel-codrea** [comment]
You can use `(navigator.userAgent.toLowerCase().indexOf('msie 6') != -1) && (navigator.userAgent.toLowerCase().indexOf('msie 7') == -1)` instead of `$.browser.msie && parseInt($.browser.version, 10) <= 6` on line 136.
Hope this helps!

**Comment by jamieholst** [comment]
The plugin has been updated to fix this.

Thanks everyone
