### ISSUE TITLE
Downloaded demo scripts do not work correctly for IE 8 and Firefox.  However the demo website does work correctly.  IE 8 and Firefox show as a physical select box.

### ISSUE THREAD

**Issue by KrazyIvan** [jamieholst/selectToAutocomplete#67]

**Comment by jamieholst** [comment]
Seems to work fine in Firefox on my end. 

Which version are you using? Could you try cracking open the inspector and check for any JavaScript errors?

**Comment by KrazyIvan** [comment]
Looks like the file includes were missing the initial / in the beginning
for me.  I was using the latest version from the source... thanks for
following back up.

**Comment by jamieholst** [comment]
Glad to hear it worked out and thanks for taking the time to report :)
