### ISSUE TITLE
Plugin doesn't work in IE 8 & 9 with older jquery

### ISSUE THREAD

**Issue by derek-duncan** [jamieholst/selectToAutocomplete#68]
We're using jquery 1.6.4 with jquery ui 1.11.0. This plugin works beautifully on all major browsers, but when tested on IE 8 & 9, the select box never converts to the autocomplete box. There are no errors in the console as well.

Any input would be appreciated.

Thanks

**Comment by jamieholst** [comment]
The plugin has been updated to be compatible with the latest 1.x version of jQuery. For compatibility with older versions of jQuery, you can try out older versions of the plugin, e.g. https://github.com/JamieAppleseed/selectToAutocomplete/tree/877240dd6b405a8b53b8d89898ebbfab09e1c170

Hope it works out!
