### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by levipadre** [jamieholst/selectToAutocomplete#71]
Hi,

This plugin are very good, thank you.
Could you help me how can I highlight the typed characters in the result (like Google search)?

Thanks,
L

**Comment by jamieholst** [comment]
Hi Levipadre,

This will all depend on which autocomplete plugin you decide to use with selectToAutocomplete. The autocomplete plugin that is bundled in the demo is jQuery UI, which unfortunately doesn't offer a feature to highlight the typed characters in the results. However, you're in no way limited to using this autocomplete plugin, selectToAutocomplete will work with any autocomplete plugin as long as you write a simple adapter for it. So you can either try extending jQuery UI or switch to an autocomplete plugin which supports keyword highlighting.

Best regards,
Jamie

**Comment by levipadre** [comment]
Thank you!

I solved it.

**Comment by jamieholst** [comment]
Happy to hear!

Have a good day, sir :)
