### ISSUE TITLE
Configure values with external datas

### ISSUE THREAD

**Issue by pomeh** [jamieholst/selectToAutocomplete#8]
It would be nice to be able to configure the values allowed via an external Javascript object and not by reading the HTML code. This way, we could:
- put data in an external file,
- remove strong coupling between HTML and datas,
- reuse data across different forms,
- create, share and reuse common values, like Country values etc,

What do you think ?

**Comment by jamieholst** [comment]
I'm not opposed to the idea of having this as an optional feature you can enable by passing in a url or something in the options hash. 

There's certainly some benefits although I think there's one major drawback: initialization becomes messy. You'd either have to: 
1. Block page loading until the external request has loaded (highly dangerous approach in case the server – for whatever reason – doesn't respond instantly), or
2. Replace the select-tag after page load, which means the user would see a drop-down first and then suddenly that is turned into a text field which could be confusing to the user, or
3. Throw out progressive enhancement, which would defeat the purpose of the plugin.

So while I'm not opposed to the idea, I'm not sure how it could be implemented in an elegant way. I'll keep the issue open for now in case someone smarter than me can think of a good way to handle initialization :)

**Comment by pomeh** [comment]
I was thinking about something similar to what it's used in the [jQuery.ui datepicker plugin](http://jqueryui.com/demos/datepicker/#localization). There are several ways to pass data, it looks like this:

``` javascript
// let the user get the config the way he wants
// here, the config is available in the datepicker data,
// but it could be also another script which load the data (see above)
var config = $.datepicker.regional[ "fr" ];

// one, once for every time
$.datepicker.setDefaults( config );

// two, on initialization
$( "#datepicker" ).datepicker( config );

// three, after initialization (may be overkill in this case)
$( "#datepicker" ).datepicker( "option", config );
```

About data loading, may be something similar to this could be use:

``` html
<!-- load the plugin -->
<script src="jquery.select-to-autocomplete.js"></script>

<!-- load your data, can be both inline or remote scipt -->
<!-- remote would be better as it enables caching and easy sharing -->
<script>
var countryChoices = {}; // build the object

// different ways to load data into the plugin
$.selectToAutocomplete.registerChoices( 'country', countryChoices);
$.selectToAutocomplete.choices.country = countryChoices;
</script>

<!-- initialize the plugin -->
<script>
(function( $, undefined ) {
$(function() {

$('select').selectToAutocomplete({
    'choices': 'country'
    // or, with the datepicker way
    // 'choices': $.selectToAutocomplete.data.country
});

}):
})(jQuery);
</script>
```

What do you think ?

**Comment by jamieholst** [comment]
The intention of the plugin is to turn a select-tag into an autocomplete field, hence the name selectToAutocomplete.

If the select-tag's original options aren't used, then it would seem slightly pointless to implement the selectToAutocomplete plugin at all. Instead, a much simpler solution that just replace your drop-down with an autocomplete-enabled text field could achieve the same goal, like this (not tested):

``` javascript
var $select_field = $( '#some-id' );
var $text_field = $( "<input></input>" );
var attrs = {};
var raw_attrs = $select_field[0].attributes;
for (var i=0; i < raw_attrs.length; i++) {
  var key = raw_attrs[i].nodeName;
  var value = raw_attrs[i].nodeValue;
  attrs[key] = raw_attrs[i].nodeValue;
};
$text_field.attr( attrs )
  .val( $select_field.find('option:selected:first').text() )
  .insertAfter( $select_field )
  .autocomplete({
    myOption: 'value'
  });
$select_field.remove();
```

Ultimately, I don't think the functionality truly belongs in the selectToAutocomplete plugin. Maybe a spin-off solution that achieves this specific goal would make more sense..?

Note: I'm closing this issue for now, but feel free to continue the discussion. Healthy debates and good arguments always have the possibility of changing a mind :)
