### ISSUE TITLE
Spurious reference to jQuery.tooltip in code

### ISSUE THREAD

**Issue by MarcusJT** [jamieholst/selectToAutocomplete#9]
One of the very last lines is an error message which references "jQuery.tooltip" - I suggest that this is a mistake and should be corrected/removed appropriately.

**Comment by pomeh** [comment]
This has been fixed by a recent commit [0627a](https://github.com/JamieAppleseed/selectToAutocomplete/commit/0627a271d1ca2ddbcf274bde04f219c224a854e5)

**Comment by jamieholst** [comment]
Thanks for the heads up MarcusJT. As pomeh mentions, this was fixed in a recent commit (version 1.0.1 of the plugin).
